# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMCsample2 <- function(Xv, Total, N, M, M1, K, Av, Wv, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq) {
    .Call(`_iNMF_MCMCsample2`, Xv, Total, N, M, M1, K, Av, Wv, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq)
}

MCMCsample2alpha <- function(Xv, Total, N, M, M1, K, Av, updateA, Wv, alpha, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq) {
    .Call(`_iNMF_MCMCsample2alpha`, Xv, Total, N, M, M1, K, Av, updateA, Wv, alpha, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq)
}

truncatedlikelihoodnoalpha <- function(Av, Wv, Xv, lambda, N, M, K) {
    .Call(`_iNMF_truncatedlikelihoodnoalpha`, Av, Wv, Xv, lambda, N, M, K)
}

fitfixedpoint <- function(Xv, lambda, N, M, M1, Av, Wv, K) {
    .Call(`_iNMF_fitfixedpoint`, Xv, lambda, N, M, M1, Av, Wv, K)
}

fitfixedpointAlpha <- function(Xv, lambda, N, M, M1, Av, updateA, Wv, K, alpha) {
    .Call(`_iNMF_fitfixedpointAlpha`, Xv, lambda, N, M, M1, Av, updateA, Wv, K, alpha)
}

Ksphere <- function(K) {
    .Call(`_iNMF_Ksphere`, K)
}

c2cpp <- function(X, n, m) {
    .Call(`_iNMF_c2cpp`, X, n, m)
}

m3tildcpp <- function(X, W, C2, m1, a0, n, m, p) {
    .Call(`_iNMF_m3tildcpp`, X, W, C2, m1, a0, n, m, p)
}

Npowercpp <- function(N, m3, theta, p) {
    .Call(`_iNMF_Npowercpp`, N, m3, theta, p)
}

lambdacpp <- function(p, m3, theta) {
    .Call(`_iNMF_lambdacpp`, p, m3, theta)
}

