# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMCsample2 <- function(Xv, Total, N, M, M1, K, Av, Wv, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq) {
    .Call('_iNMF_MCMCsample2', PACKAGE = 'iNMF', Xv, Total, N, M, M1, K, Av, Wv, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq)
}

MCMCsample2alpha <- function(Xv, Total, N, M, M1, K, Av, updateA, Wv, alpha, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq) {
    .Call('_iNMF_MCMCsample2alpha', PACKAGE = 'iNMF', Xv, Total, N, M, M1, K, Av, updateA, Wv, alpha, Mccount, burnin, EqS, EqSKappa, EqSTau, EqKappa, EqKappasq, EqTau, EqTausq, EqOmegaKappasq, EqOmegaKappaTau, EqOmegaTausq)
}

truncatedlikelihoodnoalpha <- function(Av, Wv, Xv, lambda, N, M, K) {
    .Call('_iNMF_truncatedlikelihoodnoalpha', PACKAGE = 'iNMF', Av, Wv, Xv, lambda, N, M, K)
}

fitfixedpoint <- function(Xv, lambda, N, M, M1, Av, Wv, K) {
    .Call('_iNMF_fitfixedpoint', PACKAGE = 'iNMF', Xv, lambda, N, M, M1, Av, Wv, K)
}

fitfixedpointAlpha <- function(Xv, lambda, N, M, M1, Av, updateA, Wv, K, alpha) {
    .Call('_iNMF_fitfixedpointAlpha', PACKAGE = 'iNMF', Xv, lambda, N, M, M1, Av, updateA, Wv, K, alpha)
}

Ksphere <- function(K) {
    .Call('_iNMF_Ksphere', PACKAGE = 'iNMF', K)
}

